package drools;
import rs.beerpicker.server.model.*
import rs.beerpicker.server.service.abstraction.*
import java.util.List
import java.util.ArrayList
import java.util.Arrays
dialect  "mvel"

global java.util.List beers;
global java.util.List recommendations;

rule "dish"
    when
        $beerService: BeerService();
        Dish(type == DishType.DESSERT)
    then
//        if (beers == null || beers.size() > 0) {
//            beers = $beerService.findAll();
//        }
//        recommendations.addAll($beerService.filter(beers, null, null, Arrays.asList(BeerFlavour.FRUIT, BeerFlavour.BANANA, BeerFlavour.APPLE, BeerFlavour.BERRIES, BeerFlavour.DRIED_CHERRIES, BeerFlavour.PEAR)));
//        recommendations.addAll($beerService.filter(beers, BeerType.STOUT, null, null));
//        recommendations.addAll($beerService.filter(beers, null, BeerStyle.IPA, null));
//        beers.clear();
//
        beers.addAll($beerService.findByFlavours(Arrays.asList(BeerFlavour.FRUIT, BeerFlavour.BANANA, BeerFlavour.APPLE, BeerFlavour.BERRIES, BeerFlavour.DRIED_CHERRIES, BeerFlavour.PEAR)));
        beers.addAll($beerService.findByType(BeerType.STOUT));
        beers.addAll($beerService.findByStyle(BeerStyle.IPA));
//        System.out.println("DARK MALTS, AMBER ALES");
end
