package drools;
import rs.beerpicker.server.model.*
import rs.beerpicker.server.service.abstraction.*
import java.util.List
import java.util.ArrayList
import java.util.Arrays
dialect  "mvel"

rule "dessert"
salience -2
    when
        $beer: Beer(strength > 5)
//        $food: Food($type: type, $name: name)
        $dish: Dish(type == DishType.DESSERT)
    then
        delete($beer);
end

rule "sweet"
salience -2
    when
        $beer: Beer(flavours contains BeerFlavour.OATS)
        $dish: Dish(sweetnessIndex > 3)
//        $food: Food($type: type, $name: name)
    then
        delete($beer);
end