package drools;
import rs.beerpicker.server.model.*
import rs.beerpicker.server.service.abstraction.*
import java.util.List
import java.util.ArrayList
import java.util.Arrays
dialect  "mvel"

rule "breakfast"
salience 1
    when
        $beer: Beer(strength > 4.5)
        $meal: Meal(type == MealType.BREAKFAST)
    then
        delete($beer);
end

rule "lunch"
salience 1
    when
        $beer: Beer(strength < 4.5 && strength > 6)
        $meal: Meal(type == MealType.LUNCH)
    then
        delete($beer);
end

rule "dinner"
salience 1
    when
        $beer: Beer(strength < 4.5)
        $meal: Meal(type == MealType.DINNER)
    then
        delete($beer);
end
